# Generated by Django 2.2.1 on 2019-05-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20190504_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='essential',
            field=models.BooleanField(default=False),
        ),
    ]
