# Generated by Django 2.2.1 on 2019-05-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20190516_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='contents',
            field=models.CharField(max_length=2000),
        ),
    ]
