# Generated by Django 2.2.1 on 2019-05-20 07:32

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20190516_2031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.AddField(
            model_name='writer',
            name='country',
            field=django_countries.fields.CountryField(default='CA', max_length=2),
        ),
    ]
