# Generated by Django 2.2.4 on 2019-08-31 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_auto_20190831_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
